---
- name: testing
  hosts: localhost
  gather_facts: false
  tasks:
     - name: Add host
       ansible.controller.job_template:
         name: mytestjt
         inventory: "inv1"
         state: present
         validate_certs: false
         project: "Demo Project"
         playbook: "hello_world.yml"
         credential: Demo Credential
         controller_host: "192.168.122.249"      # Replace x.x.x.x with the IP of controller host 
         controller_username: "admin"    # Replace with your controller username
         controller_password: "redhat"   # Replace with your controller password
