---
- name: testing
  hosts: localhost
  gather_facts: false
  tasks:
     - name: test
       ansible.controller.project:
         name: myproject
         state: present
         validate_certs: false
         scm_type: git
         scm_url: https://github.com/prabhanjan-passwd/test_repo/
         organization: Default
         credential: git_cred
         controller_host: "192.168.122.249"      # Replace x.x.x.x with the IP of controller host 
         controller_username: "admin"    # Replace with your controller username
         controller_password: "redhat"   # Replace with your controller password
