---
- name: testing playbook
  hosts: localhost
  tasks:
       - name: task 1
         ansible.eda.decision_environment:
             name: "EURONEXT QUAY"
             description: "Image from internal quay"
             image_url: "registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest"
             credential: "QUAY"
             organization_name: "org1"
             controller_host: 192.168.122.108
             controller_username: admin
             controller_password: redhat
             state: present
