---
- name: testing
  hosts: localhost
  gather_facts: false
  tasks:
     - name: Job process
       ansible.controller.job_template:
         name: mytestjt
         inventory: "inv1"
         state: present
         validate_certs: false
         project: "Demo Project"
         playbook: "hello_world.yml"
         credential: Demo Credential
         controller_host: "192.168.122.249"      
         controller_username: "admin"    
         controller_password: "redhat"
         credentials: 
             - Demo Credential
             - vault-cred
         webhook_credential: webhook credential



         
