---
- name: Testing LDAP
  hosts: localhost
  tasks:
    - name: Testing LDAP in 2.4 version
      ansible.controller.settings:
        controller_username: admin
        controller_password: redhat
        controller_host: 192.168.122.31
        validate_certs: false
        settings: 
          AUTH_LDAP_SERVER_URI: "ldap://10.1.230.105:10389"
          AUTH_LDAP_BIND_DN: "cn=admin,dc=ansible,dc=sbr"
          AUTH_LDAP_BIND_PASSWORD: "GoodNewsEveryone"
          AUTH_LDAP_CONNECTION_OPTIONS:
            OPT_REFERRALS: 0
            OPT_NETWORK_TIMEOUT: 30
          AUTH_LDAP_USER_SEARCH:
            - "DC=ansible,DC=sbr"
            - "SCOPE_SUBTREE"
            - "(uid=%(user)s)"
          AUTH_LDAP_GROUP_SEARCH:
            - "dc=ansible,dc=sbr"
            - "SCOPE_SUBTREE"
            - "(objectClass=Group)"
          AUTH_LDAP_GROUP_TYPE: "MemberDNGroupType"
          AUTH_LDAP_GROUP_TYPE_PARAMS:
            name_attr: "cn"
            member_attr: "member"

