- name: Delete a job from Automation Controller using username and password
  hosts: localhost
  tasks:
    - name: Delete a job using Automation Controller API
      ansible.builtin.uri:
        url: "http://192.168.122.249/api/v2/jobs/15"
        method: DELETE
        user: admin
        password: redhat
        force_basic_auth: yes
        follow_redirects: all
        status_code: 204
        body_format: json
 
