---
- name: testing
  hosts: localhost
  gather_facts: false
  tasks:
     - name: Add host
       ansible.controller.host:
         name: 1.1.1.1
         inventory: "test-inv"
         state: present
    
